#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2017-2023 Team LibreELEC (https://libreelec.tv)
# Copyright (C) 2023-present Gabor Dee (dee.gabor@gmail.com)

# copy amlogic autoscript files to part1
if [ -f "$RELEASE_DIR/3rdparty/bootloader/aml_autoscript" ]; then
  mcopy $RELEASE_DIR/3rdparty/bootloader/*autoscript :: 2>&1 > /dev/null || true
fi

# copy device trees to part1
for dtb in $RELEASE_DIR/3rdparty/bootloader/device_trees $RELEASE_DIR/3rdparty/bootloader/*.dtb $RELEASE_DIR/3rdparty/bootloader/dtb.img ; do
  [ -e "$dtb" ] && mcopy -s "$dtb" ::
done

# copy openvfd_confs to part1
if [ -e "$RELEASE_DIR/3rdparty/bootloader/openvfd_confs" ]; then
  mcopy $RELEASE_DIR/3rdparty/bootloader/openvfd_confs :: 2>&1 > /dev/null || true
fi

if [ -f "$RELEASE_DIR/3rdparty/bootloader/u-boot.bin" ]; then
  echo "Writing u-boot to $(basename $DISK)"
  dd if="$RELEASE_DIR/3rdparty/bootloader/u-boot.bin" of="$DISK" conv=fsync,notrunc bs=1 count=112 >"$SAVE_ERROR" 2>&1 || show_error
  dd if="$RELEASE_DIR/3rdparty/bootloader/u-boot.bin" of="$DISK" conv=fsync,notrunc bs=512 skip=1 seek=1 >"$SAVE_ERROR" 2>&1 || show_error
fi

if [ -f "$RELEASE_DIR/3rdparty/bootloader/boot.ini" ]; then
  mcopy $RELEASE_DIR/3rdparty/bootloader/boot.ini ::
fi
