#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2017-2022 Team LibreELEC (https://libreelec.tv)
# Copyright (C) 2022-present Gabor Dee (dee.gabor@gmail.com)

# copy device trees to part1
for dtb in $RELEASE_DIR/3rdparty/bootloader/device_trees $RELEASE_DIR/3rdparty/bootloader/*.dtb $RELEASE_DIR/3rdparty/bootloader/dtb.img ; do
  [ -e "$dtb" ] && mcopy -s "$dtb" ::
done

if [ -f "$RELEASE_DIR/3rdparty/bootloader/u-boot.bin" -a -f "$RELEASE_DIR/3rdparty/bootloader/bl1.bin" ]; then
  echo "Writing u-boot to $(basename $DISK)"
  dd if="$RELEASE_DIR/3rdparty/bootloader/bl1.bin" of="$DISK" conv=fsync,notrunc bs=1 count=442 >"$SAVE_ERROR" 2>&1 || show_error
  dd if="$RELEASE_DIR/3rdparty/bootloader/bl1.bin" of="$DISK" conv=fsync,notrunc bs=512 skip=1 seek=1 >"$SAVE_ERROR" 2>&1 || show_error
  dd if="$RELEASE_DIR/3rdparty/bootloader/u-boot.bin" of="$DISK" conv=fsync,notrunc bs=512 seek=64 >"$SAVE_ERROR" 2>&1 || show_error
fi

if [ -f "$RELEASE_DIR/3rdparty/bootloader/boot.ini" ]; then
  mcopy $RELEASE_DIR/3rdparty/bootloader/boot.ini ::
fi

if [ -f "$RELEASE_DIR/3rdparty/bootloader/config.ini" ]; then
  mcopy $RELEASE_DIR/3rdparty/bootloader/config.ini ::
fi

if [ -f "$RELEASE_DIR/3rdparty/bootloader/boot-logo.bmp.gz" ]; then
  mcopy $RELEASE_DIR/3rdparty/bootloader/boot-logo.bmp.gz ::
fi
