#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2016-2023 kszaq (kszaquitto@gmail.com)
# Copyright (C) 2023-present Gabor Dee (dee.gabor@gmail.com)

# Check for WeTek boot device selection method
if $(fw_printenv whereToBootFrom 2&>1 > /dev/null); then
  fw_setenv whereToBootFrom internal
else
  if ! $(fw_printenv libreelec 2&>1 > /dev/null); then
    fw_setenv libreelec 'run librefromsd; run librefromusb'
    fw_setenv sddtb 'if fatload mmc 0 ${dtb_mem_addr} dtb.img; then else store dtb read $dtb_mem_addr; fi'
    fw_setenv usbdtb 'if fatload usb 0 ${dtb_mem_addr} dtb.img; then else store dtb read $dtb_mem_addr; fi'
    fw_setenv librefromsd 'mmcinfo; if fatload mmc 0 ${loadaddr} kernel.img; then run sddtb; setenv bootargs ${bootargs} bootfromsd; bootm; fi'
    fw_setenv librefromusb 'usb start 0; if fatload usb 0 ${loadaddr} kernel.img; then run usbdtb; setenv bootargs ${bootargs} bootfromusb; bootm; fi'
    fw_setenv bootcmd 'if test ${bootfromnand} = 1; then setenv bootfromnand 0; saveenv; else run libreelec; fi; run storeboot'
  fi
  fw_setenv bootfromnand 1
fi

echo "Your system will try to boot from internal NAND or eMMC during the next boot."

read -p "Would you like to reboot now [Y/n]? " choice
case "$choice" in
  [nN]*)
    ;;
  *)
    reboot
    ;;
esac
