#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2016-2023 kszaq (kszaquitto@gmail.com)
# Copyright (C) 2023-present Gabor Dee (dee.gabor@gmail.com)

# Check for WeTek boot device selection method
if $(fw_printenv whereToBootFrom 2&>1 > /dev/null); then
  fw_setenv whereToBootFrom internal
else
  if ! $(fw_printenv startfromext 2&>1 > /dev/null); then
    fw_setenv startfromsd 'if mmcinfo; then if fatload mmc 0 ${loadaddr} kernel.img; then setenv bootargs ${bootargs} bootfromsd; bootm; fi; fi'
    fw_setenv startfromext 'if test ${bootfromnand} = 1; then setenv bootfromnand 0; saveenv; exit; fi; if test ${reboot_mode} = switch_system; then exit; fi; run startfromsd'
    fw_setenv bootcmd 'run startfromext; run storeboot'
  fi
  fw_setenv bootfromnand 1
fi

fw_setenv reboot_mode switch_system

echo "Your system will try to boot from internal NAND or eMMC during the next boot."

read -p "Would you like to reboot now [Y/n]? " choice
case "$choice" in
  [nN]*)
    ;;
  *)
    reboot
    ;;
esac
